[llm_services.glossary]
provider_type = "openai"
base_url = "https://api.deepseek.com"
api_key = "sk-f677192f3675409dbb1e0a49761d48c1"
model = "deepseek-chat"
timeout = 600

# [llm_services.text]
# provider_type = "openai"
# base_url = "http://192.168.31.158:8800/v1"
# api_key = "yexi12345"
# model = "gemini-3.1-pro"
# timeout = 600

[llm_services.text]
provider_type = "volcengine"
base_url = "https://api.deepseek.com"
api_key = "sk-f677192f3675409dbb1e0a49761d48c1"
model = "deepseek-chat"
timeout = 600

[llm_services.plugin_text]
provider_type = "openai"
base_url = "https://api.deepseek.com"
api_key = "sk-f677192f3675409dbb1e0a49761d48c1"
model = "deepseek-reasoner"
timeout = 600

[glossary_extraction]
role_chunk_blocks = 10
role_chunk_lines = 3

[glossary_translation]
worker_count = 300
rpm = 300

[glossary_translation.role_name]
retry_count = 3
retry_delay = 1
response_retry_count = 3
system_prompt_file = "prompts/glossary_role_name_system.txt"

[glossary_translation.display_name]
chunk_size = 60
retry_count = 3
retry_delay = 1
response_retry_count = 3
system_prompt_file = "prompts/glossary_display_name_system.txt"

[translation_context]
token_size = 1024
factor = 3.5
max_command_items = 5

[plugin_text_analysis]
worker_count = 50
rpm = 50
retry_count = 3
retry_delay = 2
response_retry_count = 3
system_prompt_file = "prompts/plugin_text_analysis_system.txt"

[text_translation]
worker_count = 200
rpm = 200
retry_count = 3
retry_delay = 2
system_prompt_file = "prompts/text_translation_system.txt"
