"""Skill 执行协议回归测试。"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def test_att_mz_skill_defines_two_round_subagent_protocol() -> None:
    """Skill 必须约束两轮子代理流程和主代理术语表审核责任。"""
    text = (ROOT / "skills" / "att-mz" / "SKILL.md").read_text(encoding="utf-8")

    required_phrases = [
        "必须启用子代理并行处理",
        "才允许串行处理",
        "子代理轮次固定为两轮",
        "### 第一轮：术语候选",
        "术语表翻译必须由主代理亲自把关",
        "`terminology/subtasks/sources/speaker_and_actor_terms.json`",
        "`terminology/subtasks/candidates/item_terms.json`",
        "主代理必须等待全部术语候选子代理完成",
        "主代理必须严审信达雅、日文句意、中文自然度、专名统一、跨类别一致性和游戏 UI 语感",
        "主代理必须亲自修改候选译名并合并到 `terminology/field-terms.json`，同时维护 `terminology/glossary.json`",
        "`terminology/field-terms.json` 的 value 是最终写进游戏字段的完整文本",
        "不能指望正文术语表补回来",
        "术语候选子代理任务单",
        "### 第二轮：三类外部规则",
        "`plugin-rules` 子代理",
        "`event-command-rules` 子代理",
        "`note-tag-rules` 子代理",
        "### 编码与 Windows 终端",
        "所有工作区 JSON、临时脚本、手动填写译文表、规则文件和交付报告都必须按 UTF-8 读写",
        "禁止依赖 Windows 默认编码、ANSI、GBK 或 Shift-JIS",
        "json.dumps(..., ensure_ascii=False)",
        "[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()",
        "禁止继续导入、翻译或写回乱码数据",
        "必须核验 Unicode code point 或原始字节",
        "`--json` 命令的 stdout 只读取最终 JSON",
        "stderr 持续输出无 ANSI 文本进度条",
        "不要把 stderr 进度行当成命令结果 JSON",
        "### 只按任务文件和命令结果工作",
        "`references/rpg-maker-mv-mz-world-knowledge.md`",
        "翻译任务中，只按 CLI 输出、工作区 JSON、游戏目录和用户明确提供的信息判断",
        "所有业务数据进出只走 CLI、`<工作区>` JSON、CLI 已保存到当前游戏状态的规则和游戏目录文件",
        "### 执行前需要知道什么",
        "RPG Maker MV/MZ",
        "不需要知道：源码、程序内部数据、模型提示词怎样生成、占位符怎样恢复",
        "### 输入-逻辑-输出总则",
        "每个阶段开始前，必须先明确“输入是什么、处理逻辑是什么、输出什么”",
        "### 命令 I/O 合约",
        "`doctor --no-check-llm --json`",
        "`doctor --game <游戏标题> --no-check-llm --json`",
        "`prepare-agent-workspace --game <游戏标题> --output-dir <工作区> --json`",
        "`scan-placeholder-candidates --game <游戏标题> --input <规则文件> --json`",
        "`import-placeholder-rules --game <游戏标题> --input <规则文件> --json`",
        "`import-terminology --game <游戏标题> --input <字段译名表> --glossary-input <正文术语表> --json`",
        "`import-plugin-rules --game <游戏标题> --input <规则文件> --json`",
        "`import-event-command-rules --game <游戏标题> --input <规则文件> --json`",
        "`export-note-tag-candidates --game <游戏标题> --output <文件> --json`",
        "`validate-note-tag-rules --game <游戏标题> --input <规则文件> --json`",
        "`import-note-tag-rules --game <游戏标题> --input <规则文件> --json`",
        "`quality-report --game <游戏标题> --json`",
        "`export-quality-fix-template --game <游戏标题> --output <文件> --json`",
        "生成可填写的修复表",
        "`export-untranslated-translations --game <游戏标题> --output <文件> --json`",
        "一次导出全部还没成功保存译文的原文，生成可填写的译文表",
        "不传 `--limit` 时导出全部",
        "`validate-japanese-residual-rules --game <游戏标题> --input <规则文件> --json`",
        "`import-japanese-residual-rules --game <游戏标题> --input <规则文件> --json`",
        "禁止全局关闭日文残留检测",
        "`write-back --game <游戏标题> --json`",
        "用户是否允许覆盖字体必须单独确认",
        "禁止使用 `--confirm-font-overwrite`",
        "`write-back --game <游戏标题> --confirm-font-overwrite --json`",
        "`restore-font --game <游戏标题> --json`",
        "默认不覆盖字体引用",
        "对比激活版和原件留档",
        "`--replacement-font-path <字体文件>`",
        "第一次写进游戏文件得到的是可试玩汉化结果，不是百分百完成承诺",
        "## 5. 试玩反馈迭代流程",
        "试玩反馈是正式翻译流程的一部分",
        "先向用户收集最小可定位信息",
        "每轮反馈修复都必须走“导出可填写文件或规则文件 -> 修改 -> validate/import -> quality-report -> 用户确认是否再次写进游戏文件”的闭环",
        "用户试玩反馈不是翻译失败本身",
        "把第一版可试玩汉化结果包装成“百分百完成”",
        "### 工作区 JSON 格式契约",
        "`placeholder-rules.json`：顶层必须是对象，格式为 `{正则表达式: 占位符模板}`",
        "禁止写成 `{占位符名: 正则表达式}`",
        "`terminology/field-terms.json`：这是“字段译名表”",
        "`terminology/glossary.json`：这是“正文术语表”",
        "`source == translated` 是合法术语",
        "正文术语表必须只保留 `terms` 顶层对象",
        "字段包装形式不得写入正文术语表",
        "字段译名表负责写回地图显示名、数据库名称、系统类型，以及 MZ 标准 `101.parameters[4]` 名字框等游戏字段",
        "正文术语表负责正文翻译提示词命中",
        "`plugin-rules.json`：顶层必须是对象，格式为 `{插件名: [JSONPath, ...]}`",
        "JSONPath 必须使用括号路径语法并从 `$['parameters']` 开始",
        "禁止使用 `$.xxx` 点号路径",
        "`event-command-rules.json`：顶层必须是对象，格式为 `{指令编码字符串: [{match, paths}]}`",
        "`note-tag-rules.json`：顶层必须是对象，格式为 `{data文件名或文件模式: [note标签名, ...]}`",
        "`{\"<data文件名>.json\": [\"<玩家可见说明标签>\"], \"<地图文件模式>\": [\"<玩家可见名牌标签>\"]}`",
        "不能把某个标签名当成所有游戏通用答案",
        "`pending-translations.json`：这是“还没成功保存译文的文本表”。顶层是 `{location_path: 条目对象}`",
        "导入前只填写 `translation_lines` 字符串数组",
        "`long_text` 是多行对话，可以按自然语义填写，导入命令会按当前 `[text_rules]` 行宽配置自动拆短",
        "`quality-fix-template.json`：这是“检查没通过译文的修复表”",
        "`manual_fill_note` 是填写提示，`text_for_model_lines` 只供对照",
        "填写 `translation_lines` 时只能使用 `original_lines` 里的游戏原始控制符",
        "`reset-translations.json`：顶层必须是 `{\"location_paths\": [\"<定位路径>\"]}`",
        "`reset-translations --game <游戏标题> --all --json`",
        "完整重译不要手工导出全集路径",
        "已导入规则回填文件",
        "禁止用空 `translation_lines` 当重置信号",
        "`japanese-residual-rules.json`：这是“允许保留日文的例外表”。顶层是 `{location_path: {allowed_terms, reason}}`",
        "`allowed_terms` 是允许原样保留的日文片段字符串数组",
        "禁止在 `pending-translations.json` 内新增例外字段",
        "### 控制符字符级保留",
        "都必须当成不可翻译标记",
        r"原文是 `\F3[66」「` 时，译文也必须保留 `\F3[66」「`",
        r"禁止改成 `\F3[66]「`",
        r"禁止改成 `\F3[60」「`",
        "如果 CLI 报 `疑似控制符不一致`",
        "占位符规则由主代理亲自处理",
        "基于当前会进入正文翻译的完整文本集合生成草稿",
        "`summary.uncovered_count` 不等于 0 时必须修规则，不能导入或翻译",
        "正确示例：输入候选",
        "第二轮子代理任务契约",
        "格式为 `{正则表达式: 占位符模板}`",
        "格式为 `{插件名: [JSONPath, ...]}`",
        "主代理必须等待三类规则子代理全部完成",
        "三类外部规则全部导入后，主代理才能重新运行 `build-placeholder-rules`",
        "亲自审查、校验、覆盖扫描并导入占位符规则",
        "任一术语候选或规则子代理未完成、失败或校验未通过，或占位符规则未最终导入，不启动翻译",
        "### 插件依赖文本型字符串的兼容策略",
        "项目层不阻止地图显示名、数据库名称、系统类型，以及 MZ 标准名字框等字段汉化",
        "必须主动检查插件或脚本是否把名字框、地图显示名、数据库名称、系统类型或其他文本型字符串当作功能触发键使用",
        "MV 说话人字段通常要从插件或文本规则里确认，不能默认补写 `101.parameters[4]`",
        "建立“中文显示值 -> 原始触发值”的兼容映射",
        "不得把例外游戏逻辑写进 A.T.T MZ 项目核心",
        "### 子代理上下文包",
        "不要把大 JSON 正文塞进子代理 prompt",
        "只允许写自己负责的输出文件",
        "完成后必须报告：改动文件、是否为空结果、空结果理由、未解决风险、建议主代理运行的校验命令",
        "推荐子代理 prompt 模板",
        "### 三类规则任务单模板",
        "`docs/plugin-rules-agent-prompt.md`",
        "`docs/event-command-rules-agent-prompt.md`",
        "`plugin-rules` 子代理任务单",
        "`event-command-rules` 子代理任务单",
        "`note-tag-rules` 子代理任务单",
        "### 子代理最佳工作示例",
        "必须复制对应任务单和本节示例",
        "错误示例",
        "{\"(?i)\\\\\\\\N\\\\d*\"",
        "小写 `\\n` 是游戏文本中的字面量换行，已由项目内置规则保护",
        "处理裸大写 `\\N` 插件标记时不得使用 `(?i)` 忽略大小写",
        "输入：读取 <工作区>/terminology/subtasks/sources/<术语分组>.json、<工作区>/terminology/contexts/speakers/*.json",
        "不确定项也必须给出当前最合理译名",
        "$['parameters']['entries'][*]['label']",
        "资源路径、脚本、数字、颜色、布尔值和内部标识都排除",
        "code=357 parameters = [插件名, 指令名, 显示名, 参数对象]",
        "MV 默认导出 `356`",
        "$['parameters'][3]['messageText']",
        "$['parameters'][2]",
        "输入片段: {\"file_name\": \"<物品数据文件>.json\", \"tag_name\": \"<玩家可见说明标签>\"",
        "正确输出: {\"<物品数据文件>.json\": [\"<玩家可见说明标签>\"], \"<技能数据文件>.json\": [\"<玩家可见补充说明标签>\"], \"<地图文件模式>\": [\"<玩家可见名牌标签>\"]}",
        "同一个标签名在不同游戏里含义可能不同",
        "脚本、公式、资源名、ID、枚举、装备状态编号、连锁技能编号",
        "要查看最新一轮“模型翻了但项目检查没通过”的全部错误明细",
        "`export-quality-fix-template --game <游戏标题> --output <工作区>/quality-fix-template.json --json`",
        "`reset-translations --game <游戏标题> --input <工作区>/reset-translations.json --json`",
        "## 13. 检查失败后的处理",
        "`validate-* --json` 返回 `error` 时",
        "先把错误映射回对应工作区 JSON",
        "误用了 `$.xxx` 点号路径",
        "`note_tag_rules_invalid`",
        "`japanese_residual_rules_invalid`",
        "`quality-report --json` 返回 `japanese_residual_items`",
        "推荐先用 `export-quality-fix-template --json` 生成可填写的修复表",
        "必须用 `reset-translations` 的 `location_paths` 显式文件",
        "write-back --game <游戏标题> --json",
        "禁止绕过 CLI 手改项目数据",
        "直接改游戏 `data/*.json` 的 `note` 字段",
    ]
    for phrase in required_phrases:
        assert phrase in text

    forbidden_sample_phrases = [
        "拡張説明",
        "ExtendDesc",
        "namePop",
        "upgrade",
        "ChainSkill",
        "EquipState",
        "Items.json",
        "Weapons.json",
        "Skills.json",
        "Map*.json",
        "五类子代理",
        "主代理必须亲自修改候选译名并合并到 `terminology/" + "terms" + ".json`",
        "`terminology` 子代理：读取 `terminology/" + "terms" + ".json`",
        "只写 `terminology/" + "terms" + ".json`",
        "aliases",
        "别名",
        "### 四类子代理任务契约",
        "主代理必须等待四类子代理全部完成",
        "四类子代理全部导入后",
        "references/rmmz-world-knowledge.md",
        "`placeholder-rules` 子代理",
        "`placeholder-rules` 子代理任务单",
        "主 Agent",
        "外部 Agent",
        "并行任务",
        "主执行者",
        "子任务执行者",
        "你必须",
        "人工处理者",
        "人工填写",
    ]
    for phrase in forbidden_sample_phrases:
        assert phrase not in text


def test_rule_agent_prompt_documents_exist_and_define_cli_contracts() -> None:
    """三类规则子代理引用的外部任务契约文档必须可直接执行。"""
    plugin_text = (ROOT / "docs" / "plugin-rules-agent-prompt.md").read_text(encoding="utf-8")
    event_text = (ROOT / "docs" / "event-command-rules-agent-prompt.md").read_text(encoding="utf-8")

    plugin_required_phrases = [
        "不读取项目源码、数据库或程序内部对象",
        "`<工作区>/plugins.json`",
        "唯一可写文件：`<工作区>/plugin-rules.json`",
        "格式为 `{插件名: [JSONPath, ...]}`",
        "JSONPath 必须使用括号路径语法",
        "合法空结果是 `{}`",
        "validate-plugin-rules",
        "改动文件",
        "未解决风险",
    ]
    for phrase in plugin_required_phrases:
        assert phrase in plugin_text

    event_required_phrases = [
        "不读取项目源码、数据库或程序内部对象",
        "`<工作区>/event-commands.json`",
        "MV 工作区未显式指定编码时通常导出 `356` 插件命令",
        "MZ 工作区通常导出 `357` 插件命令",
        "唯一可写文件：`<工作区>/event-command-rules.json`",
        "格式为 `{指令编码字符串: [{match, paths}]}`",
        "`match` 的键必须是参数索引字符串",
        "没有过滤条件时，`match` 写 `{}`",
        "JSONPath 必须使用括号路径语法",
        "合法空结果是 `{}`",
        "validate-event-command-rules",
        "未解决风险",
    ]
    for phrase in event_required_phrases:
        assert phrase in event_text

    forbidden_real_context_phrases = [
        "C:\\",
        "D:\\",
        "Users\\",
        "测试样本",
        "Sexual_conflict",
        "生意気",
    ]
    combined_text = plugin_text + event_text
    for phrase in forbidden_real_context_phrases:
        assert phrase not in combined_text


def test_text_translation_prompt_keeps_protocol_minimal() -> None:
    """正文翻译提示词只说明可见任务，不解释项目内部保护机制。"""
    text = (ROOT / "prompts" / "text_translation_system.md").read_text(encoding="utf-8")

    required_phrases = [
        "`[[术语表]]`",
        "`short_text`：按一个完整字段翻译，`translation_lines` 必须只包含 1 个字符串",
        "形如 `[RMMZ_...]` 或 `[CUSTOM_...]` 的片段是必须原样保留的文本标记。",
    ]
    for phrase in required_phrases:
        assert phrase in text

    forbidden_phrases = [
        "# 术语表",
        "如果原文内部已有换行",
        "常用于变量",
        "保护",
        "恢复",
        "写回",
        "占位符",
    ]
    for phrase in forbidden_phrases:
        assert phrase not in text
