"""Skill 执行协议回归测试。"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def test_att_mz_skill_requires_parallel_subagents_when_available() -> None:
    """支持子代理的平台必须并行处理外部分析任务。"""
    text = (ROOT / "skills" / "att-mz" / "SKILL.md").read_text(encoding="utf-8")

    required_phrases = [
        "必须启用子代理并行处理",
        "才允许串行处理",
        "`placeholder-rules` 子代理",
        "`name-context` 子代理",
        "`plugin-rules` 子代理",
        "`event-command-rules` 子代理",
        "`note-tag-rules` 子代理",
        "### 编码与 Windows 终端",
        "所有工作区 JSON、临时脚本、手动填写译文表、规则文件和交付报告都必须按 UTF-8 读写",
        "禁止依赖 Windows 默认编码、ANSI、GBK 或 Shift-JIS",
        "json.dumps(..., ensure_ascii=False)",
        "[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()",
        "禁止继续导入、翻译或写回乱码数据",
        "必须核验 Unicode code point 或原始字节",
        "### 黑盒执行原则",
        "翻译任务中，把本项目当成闭源黑盒工具使用",
        "所有业务数据进出只走 CLI、`<工作区>` JSON、当前游戏数据库中已导入的规则和游戏目录文件",
        "### 输入-逻辑-输出总则",
        "主 Agent 执行每个阶段前，必须先明确“输入是什么、处理逻辑是什么、输出什么”",
        "### 命令 I/O 合约",
        "`doctor --no-check-llm --json`",
        "`prepare-agent-workspace --game <游戏标题> --output-dir <工作区> --json`",
        "`export-note-tag-candidates --game <游戏标题> --output <文件> --json`",
        "`validate-note-tag-rules --game <游戏标题> --input <规则文件> --json`",
        "`import-note-tag-rules --game <游戏标题> --input <规则文件> --json`",
        "`quality-report --game <游戏标题> --json`",
        "`export-quality-fix-template --game <游戏标题> --output <文件> --json`",
        "生成可填写的修复表",
        "`export-untranslated-translations --game <游戏标题> --output <文件> --json`",
        "一次导出全部还没成功保存译文的原文，生成可填写的译文表",
        "不传 `--limit` 时导出全部",
        "`validate-japanese-residual-rules --game <游戏标题> --input <规则文件> --json`",
        "`import-japanese-residual-rules --game <游戏标题> --input <规则文件> --json`",
        "禁止全局关闭日文残留检测",
        "`write-back --game <游戏标题> --json`",
        "用户是否允许覆盖字体必须单独确认",
        "禁止使用 `--confirm-font-overwrite`",
        "`write-back --game <游戏标题> --confirm-font-overwrite --json`",
        "`restore-font --game <游戏标题> --json`",
        "默认不覆盖字体引用",
        "没有记录时不猜测原字体",
        "### 工作区 JSON 格式契约",
        "`placeholder-rules.json`：顶层必须是对象，格式为 `{正则表达式: 占位符模板}`",
        "禁止写成 `{占位符名: 正则表达式}`",
        "`name-context/name_registry.json`：顶层只使用 `speaker_names` 和 `map_display_names` 两个对象",
        "`plugin-rules.json`：顶层必须是对象，格式为 `{插件名: [JSONPath, ...]}`",
        "JSONPath 必须使用括号路径语法并从 `$['parameters']` 开始",
        "禁止使用 `$.xxx` 点号路径",
        "`event-command-rules.json`：顶层必须是对象，格式为 `{指令编码字符串: [{match, paths}]}`",
        "`note-tag-rules.json`：顶层必须是对象，格式为 `{基础数据库文件名: [note标签名, ...]}`",
        "`{\"Items.json\": [\"拡張説明\", \"ExtendDesc\"], \"Weapons.json\": [\"拡張説明\"]}`",
        "`upgrade`、`ChainSkill`、`EquipState`",
        "`pending-translations.json`：这是“还没成功保存译文的文本表”。顶层是 `{location_path: 条目对象}`",
        "导入前只填写 `translation_lines` 字符串数组",
        "`long_text` 是多行对话，可以按自然语义填写，导入命令会按当前 `[text_rules]` 行宽配置自动拆短",
        "`quality-fix-template.json`：这是“检查没通过译文的修复表”",
        "`reset-translations.json`：顶层必须是 `{\"location_paths\": [\"<定位路径>\"]}`",
        "`reset-translations --game <游戏标题> --all --json`",
        "完整重译不要手工导出全集路径",
        "已导入规则回填文件",
        "禁止用空 `translation_lines` 当重置信号",
        "`japanese-residual-rules.json`：这是“允许保留日文的例外表”。顶层是 `{location_path: {allowed_terms, reason}}`",
        "`allowed_terms` 是允许原样保留的日文片段字符串数组",
        "禁止在 `pending-translations.json` 内新增例外字段",
        "### 控制符字符级保留",
        "未被替换的裸露片段必须字符级照抄原文",
        r"原文是 `\F3[66」「` 时，译文也必须保留 `\F3[66」「`",
        r"禁止改成 `\F3[66]「`",
        r"禁止改成 `\F3[60」「`",
        "如果 CLI 报 `疑似控制符不一致`",
        "### 五类子代理任务契约",
        "主 Agent 派发子代理时，必须把对应行的输入、逻辑和输出写进子代理 prompt",
        "格式为 `{正则表达式: 占位符模板}`",
        "格式为 `{插件名: [JSONPath, ...]}`",
        "主 Agent 必须等待五类子代理全部完成",
        "任一子代理未完成、失败或校验未通过，不启动翻译",
        "### 子代理上下文包",
        "不要把大 JSON 正文塞进子代理 prompt",
        "只允许写自己负责的输出文件",
        "完成后必须报告：改动文件、是否为空结果、空结果理由、未解决风险、建议主 Agent 运行的校验命令",
        "推荐子代理 prompt 模板",
        "### 子代理任务单模板",
        "`placeholder-rules` 子代理任务单",
        "`name-context` 子代理任务单",
        "`plugin-rules` 子代理任务单",
        "`event-command-rules` 子代理任务单",
        "`note-tag-rules` 子代理任务单",
        "### 子代理最佳工作示例",
        "必须复制对应任务单和本节示例",
        "输入片段: {\"marker\": \"\\\\X[face_a]\"",
        "正确输出: {\"(?i)\\\\\\\\X\\\\[[^\\\\]\\\\r\\\\n]+\\\\]\"",
        "错误输出: {\"(?i)\\\\\\\\N\\\\d*\"",
        "必须读取 `speaker_contexts/*.json`",
        "完成报告必须写明读取了多少个 `speaker_contexts/*.json`",
        "$['parameters']['entries'][*]['label']",
        "资源路径、脚本、数字、颜色、布尔值和内部标识都排除",
        "code=357 parameters = [插件名, 指令名, 显示名, 参数对象]",
        "$['parameters'][3]['messageText']",
        "$['parameters'][2]",
        "输入片段: {\"file_name\": \"Items.json\", \"tag_name\": \"拡張説明\"",
        "正确输出: {\"Items.json\": [\"拡張説明\"], \"Skills.json\": [\"ExtendDesc\"]}",
        "`<拡張説明:...>`、`<ExtendDesc:...>`",
        "`<upgrade:...>`、`<ChainSkill:...>`、`<EquipState:...>`",
        "要查看最新一轮“模型翻了但项目检查没通过”的全部错误明细",
        "`export-quality-fix-template --game <游戏标题> --output <工作区>/quality-fix-template.json --json`",
        "`reset-translations --game <游戏标题> --input <工作区>/reset-translations.json --json`",
        "## 12. 检查失败后的处理",
        "`validate-* --json` 返回 `error` 时",
        "先把错误映射回对应工作区 JSON",
        "误用了 `$.xxx` 点号路径",
        "`note_tag_rules_invalid`",
        "`japanese_residual_rules_invalid`",
        "`quality-report --json` 返回 `japanese_residual_items`",
        "推荐先用 `export-quality-fix-template --json` 生成可填写的修复表",
        "必须用 `reset-translations` 的 `location_paths` 显式文件",
        "write-back --game <游戏标题> --json",
        "禁止直接改数据库",
        "直接改游戏 `data/*.json` 的 `note` 字段",
    ]
    for phrase in required_phrases:
        assert phrase in text
